Fix issue #24
developersIndia/wiki pull request #25
Opened 2022-01-01 17:51 UTC by Aniganesh

[Issue 24](https://github.com/developersIndia/wiki/issues/24) This PR if approved will add a link to the github student education package in the miscellaneous section of the README.md

2022-01-14 21:53 UTC, Jarmos-san requested changes
Looks good but could you just add the link to the GitHub Education thing & leave out the rest of changes you made as it is for now (see the other comments for reasons)? You can open another PR describing some of the formatting issues in the `.md` file.

2022-01-14 21:53 UTC, Jarmos-san commented on README.md
> -
Just curious was this dash added here mistakenly?

2022-01-14 21:53 UTC, Jarmos-san commented on README.md
> +* **Websites**
Formatting issues can be taken care of in a separate PR

2022-01-14 21:53 UTC, Jarmos-san commented on README.md
> +* [Github Student Education package](https://education.github.com)
Looks good enough but generally speaking PRs should be specific. And this one touched upon way too much stuff than what you described in the PR.

2022-07-01 05:58 UTC, Bhupesh-V commented
@Aniganesh Feel free to raise a new PR or address the comments in this one and let us know if you want it reviewed. Closing this for now.

2022-07-01 05:58 UTC, closed without merging